#5.1
library(ggplot2)
library(dplyr)
library(broom)
library(plyr)
tv<-read.csv("tv.csv")
data(tv)
relation <- lm(Sales~TV,data=tv)
summary(relation)
plot(tv$TV,tv$Sales,xlab="TV",ylab="Sales") 
abline(relation)

#5.2
library(ggplot2)
library(predict3d)
jobprof<-read.csv("jobprof.csv")
data(jobprof)
model <- lm(y~x1+x2+x3,data=jobprof)
summary(model)
ggPredict(model,se=TRUE)
